"""
musetalk_engine.py — MuseTalk lip sync wrapper

MuseTalk (ByteDance, Apache 2.0) is the best open-source lip sync model as of 2025.
- Real-time capable on T4 GPU (~30fps)
- Preserves full face quality (unlike Wav2Lip which blurs lower face)
- Handles head + neck motion naturally

Install path: models/MuseTalk/ (cloned by setup.sh)
Model weights: models/MuseTalk/models/ (downloaded from HuggingFace)

Fallback: if MuseTalk is not installed, returns False and caller falls back
to the static image video pipeline.

Pipeline:
  avatar.png + voice.wav → MuseTalk → lipsync.mp4
"""
import logging
import os
import shutil
import subprocess
import tempfile
from pathlib import Path
from typing import Optional

log = logging.getLogger("musetalk_engine")

ROOT = Path(__file__).parent.parent.resolve()
MUSETALK_DIR = ROOT / "models" / "MuseTalk"
MUSETALK_WEIGHTS = MUSETALK_DIR / "models" / "musetalk"
MUSETALK_DWPOSE  = MUSETALK_DIR / "models" / "dwpose"


# ── Availability check ────────────────────────────────────────────────────────

def is_available() -> bool:
    """Check if MuseTalk is installed and weights are present."""
    if not MUSETALK_DIR.exists():
        return False
    if not (MUSETALK_DIR / "scripts" / "inference.py").exists():
        return False
    if not MUSETALK_WEIGHTS.exists():
        return False
    return True


def install_musetalk() -> bool:
    """
    Clone MuseTalk and download weights.
    Called by setup.sh, but can also be triggered from UI.
    Returns True if successful.
    """
    MUSETALK_DIR.parent.mkdir(parents=True, exist_ok=True)

    # Clone repo
    if not MUSETALK_DIR.exists():
        log.info("Cloning MuseTalk...")
        r = subprocess.run(
            ["git", "clone", "--depth=1",
             "https://github.com/TMElyralab/MuseTalk.git",
             str(MUSETALK_DIR)],
            capture_output=True, timeout=300,
        )
        if r.returncode != 0:
            log.error(f"MuseTalk clone failed: {r.stderr.decode()[:300]}")
            return False

    # Install MuseTalk requirements (into existing venv)
    req_file = MUSETALK_DIR / "requirements.txt"
    if req_file.exists():
        log.info("Installing MuseTalk requirements...")
        subprocess.run(
            ["pip", "install", "-r", str(req_file), "--quiet"],
            timeout=300,
        )

    # Download weights from HuggingFace
    log.info("Downloading MuseTalk weights (~3.5GB)...")
    try:
        from huggingface_hub import snapshot_download
        snapshot_download(
            "TMElyralab/MuseTalk",
            local_dir=str(MUSETALK_DIR / "models"),
            ignore_patterns=["*.git*"],
        )
        log.info("MuseTalk weights downloaded")
        return True
    except Exception as e:
        log.error(f"MuseTalk weight download failed: {e}")
        return False


# ── Inference YAML builder ────────────────────────────────────────────────────

def _build_inference_yaml(
    avatar_path: Path,
    audio_path: Path,
    result_dir: Path,
    bbox_shift: int = 0,
) -> Path:
    """Build MuseTalk inference config YAML in a temp location."""
    yaml_content = f"""# MuseTalk inference config — auto-generated by Avatar Studio
task_0:
  video_path: "{str(avatar_path)}"
  audio_path: "{str(audio_path)}"
  bbox_shift: {bbox_shift}
"""
    yaml_path = result_dir / "inference_config.yaml"
    yaml_path.write_text(yaml_content)
    return yaml_path


# ── Core inference ────────────────────────────────────────────────────────────

def run_musetalk(
    avatar_path: Path,
    audio_path: Path,
    out_path: Path,
    bbox_shift: int = 0,
    fps: int = 25,
    batch_size: int = 8,    # T4 can handle 8 frames/batch comfortably
) -> bool:
    """
    Run MuseTalk lip sync.
    avatar_path: PNG image (or MP4 video) of the talking head
    audio_path:  WAV audio file (44.1kHz mono)
    out_path:    Output MP4 path
    Returns True if output video was generated successfully.
    """
    if not is_available():
        log.warning("MuseTalk not installed — use install_musetalk() first")
        return False

    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    with tempfile.TemporaryDirectory() as tmpdir:
        tmp = Path(tmpdir)
        result_dir = tmp / "results"
        result_dir.mkdir()

        # Build inference config
        yaml_path = _build_inference_yaml(avatar_path, audio_path, tmp, bbox_shift)

        # MuseTalk unet config (inside the repo)
        unet_config = MUSETALK_DIR / "configs" / "unet" / "second_stage.yaml"

        log.info(f"Running MuseTalk | avatar={avatar_path.name} audio={audio_path.name}")

        env = os.environ.copy()
        env["PYTHONPATH"] = str(MUSETALK_DIR)   # so imports resolve within MuseTalk

        cmd = [
            "python", "-m", "scripts.inference",
            "--unet_config_path", str(unet_config),
            "--inference_config", str(yaml_path),
            "--result_dir", str(result_dir),
            "--fps", str(fps),
            "--batch_size", str(batch_size),
        ]

        r = subprocess.run(
            cmd,
            cwd=str(MUSETALK_DIR),
            env=env,
            capture_output=True,
            timeout=1200,   # 20 min max for long videos
        )

        if r.returncode != 0:
            log.error(f"MuseTalk failed (rc={r.returncode}):\n{r.stderr.decode()[-600:]}")
            return False

        # MuseTalk outputs to result_dir/task_0/*.mp4
        output_files = list(result_dir.rglob("*.mp4"))
        if not output_files:
            log.error("MuseTalk ran but produced no output video")
            return False

        # Take the last/only mp4 (sometimes named task_0_final.mp4 or combined.mp4)
        output_files.sort(key=lambda p: p.stat().st_mtime, reverse=True)
        raw_output = output_files[0]

        # Re-encode with proper parameters for our pipeline
        r2 = subprocess.run(
            ["ffmpeg", "-y", "-i", str(raw_output),
             "-c:v", "libx264", "-preset", "fast", "-crf", "18",
             "-c:a", "aac", "-b:a", "128k",
             "-movflags", "+faststart",
             str(out_path)],
            capture_output=True, timeout=300,
        )

        if r2.returncode != 0 or not out_path.exists():
            log.error(f"Re-encode failed: {r2.stderr.decode()[:200]}")
            # Try just copying
            shutil.copy2(str(raw_output), str(out_path))

    ok = out_path.exists() and out_path.stat().st_size > 10240
    if ok:
        log.info(f"MuseTalk OK → {out_path} ({out_path.stat().st_size//1024}KB)")
    return ok


# ── Fallback: static image video ─────────────────────────────────────────────

def make_static_video(avatar_path: Path, audio_path: Path, out_path: Path, fps: int = 25) -> bool:
    """
    Fallback when MuseTalk is not available.
    Loops the avatar PNG for the duration of the audio.
    Not realistic but keeps the pipeline working.
    """
    try:
        r = subprocess.run(
            ["ffmpeg", "-y",
             "-loop", "1", "-i", str(avatar_path),
             "-i", str(audio_path),
             "-c:v", "libx264", "-preset", "fast", "-crf", "20",
             "-c:a", "aac", "-b:a", "128k",
             "-shortest",
             "-vf", f"fps={fps},scale=512:512:force_original_aspect_ratio=decrease,pad=512:512:(ow-iw)/2:(oh-ih)/2",
             "-movflags", "+faststart",
             str(out_path)],
            capture_output=True, timeout=300,
        )
        ok = r.returncode == 0 and out_path.exists()
        if ok:
            log.info(f"Static video fallback OK → {out_path}")
        else:
            log.error(f"Static video failed: {r.stderr.decode()[:200]}")
        return ok
    except Exception as e:
        log.error(f"make_static_video: {e}")
        return False


# ── GFPGAN face enhancement (post-process MuseTalk output) ────────────────────

def enhance_faces(video_in: Path, video_out: Path) -> bool:
    """
    Post-process MuseTalk output with GFPGAN v1.4 to clean up compression artifacts.
    Extracts frames → enhance each → reassemble.
    Only runs if gfpgan is installed (already in requirements.txt).
    """
    try:
        import cv2
        from gfpgan import GFPGANer

        with tempfile.TemporaryDirectory() as tmpdir:
            tmp = Path(tmpdir)
            frames_dir = tmp / "frames"
            enhanced_dir = tmp / "enhanced"
            frames_dir.mkdir(); enhanced_dir.mkdir()

            # Extract frames
            cap = cv2.VideoCapture(str(video_in))
            fps = cap.get(cv2.CAP_PROP_FPS) or 25
            frame_idx = 0
            while True:
                ret, frame = cap.read()
                if not ret:
                    break
                cv2.imwrite(str(frames_dir / f"{frame_idx:06d}.png"), frame)
                frame_idx += 1
            cap.release()

            if frame_idx == 0:
                return False

            # Load GFPGAN
            enhancer = GFPGANer(
                model_path=None,   # auto-downloads
                upscale=1,
                arch="clean",
                channel_multiplier=2,
            )

            # Enhance in batches of 16 for speed
            frame_files = sorted(frames_dir.glob("*.png"))
            for i, fpath in enumerate(frame_files):
                img = cv2.imread(str(fpath))
                _, _, enhanced = enhancer.enhance(
                    img, has_aligned=False, only_center_face=True, paste_back=True
                )
                out_frame = enhanced if enhanced is not None else img
                cv2.imwrite(str(enhanced_dir / fpath.name), out_frame)

                if (i + 1) % 50 == 0:
                    log.info(f"GFPGAN: {i+1}/{len(frame_files)} frames enhanced")

            # Reassemble video
            r = subprocess.run(
                ["ffmpeg", "-y",
                 "-framerate", str(fps),
                 "-i", str(enhanced_dir / "%06d.png"),
                 "-i", str(video_in),            # take audio from original
                 "-map", "0:v", "-map", "1:a",
                 "-c:v", "libx264", "-preset", "fast", "-crf", "16",
                 "-c:a", "copy",
                 "-movflags", "+faststart",
                 str(video_out)],
                capture_output=True, timeout=600,
            )
            ok = r.returncode == 0 and video_out.exists()
            if ok:
                log.info(f"GFPGAN enhancement OK → {video_out}")
            return ok

    except Exception as e:
        log.warning(f"GFPGAN enhancement failed (non-blocking): {e}")
        return False


# ── Public API ────────────────────────────────────────────────────────────────

def generate_lipsync(
    avatar_path: Path,
    audio_path: Path,
    out_path: Path,
    enhance: bool = True,
    fps: int = 25,
) -> bool:
    """
    Full lip sync pipeline.
    1. Run MuseTalk (if available)
    2. Run GFPGAN enhancement (if enhance=True)
    3. Fallback to static video if MuseTalk unavailable

    Returns True if output video was generated.
    """
    out_path = Path(out_path)
    musetalk_out = out_path.with_stem(out_path.stem + "_mt")

    if is_available():
        log.info("MuseTalk is available — running lip sync")
        mt_ok = run_musetalk(avatar_path, audio_path, musetalk_out, fps=fps)

        if mt_ok and enhance:
            log.info("Running GFPGAN face enhancement...")
            enh_ok = enhance_faces(musetalk_out, out_path)
            if not enh_ok:
                import shutil; shutil.copy2(str(musetalk_out), str(out_path))
            musetalk_out.unlink(missing_ok=True)
            return out_path.exists()
        elif mt_ok:
            import shutil; shutil.copy2(str(musetalk_out), str(out_path))
            musetalk_out.unlink(missing_ok=True)
            return True
        else:
            log.warning("MuseTalk failed — falling back to static video")

    log.info("Using static video fallback (no lip sync)")
    return make_static_video(avatar_path, audio_path, out_path, fps=fps)
